import path from 'node:path';
import { fileURLToPath } from 'node:url';
import react from '@vitejs/plugin-react';
import { configDefaults, defineConfig } from 'vitest/config';
import { devPort, portGuard } from './scripts/ports.ts';
import { projectFolder } from './scripts/project-folder.ts';

// Step 0 config (docs/DESIGN.md §6.2 item 2). Frozen after Step 0: tracks do not edit this file.

const root = fileURLToPath(new URL('.', import.meta.url));

// Watcher ignores are anchored to the project root. A glob such as '**/.claude/**' is matched against absolute
// paths, and every track worktree lives under <repo>/.claude/worktrees/, so a worktree's own dev server would
// ignore every source edit.
const skip = ['.claude', 'fixtures', 'test-results'].map((d) => path.join(root, d) + path.sep);

// 5180 only for the user's main checkout; never for agents, tests or worktrees (scripts/ports.ts, §5.5.4).
// portGuard() applies the same rule after command-line options (--port, --strictPort) have been merged.
const port = devPort(process.env, root);

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), projectFolder(), portGuard(process.env, root)],
  assetsInclude: ['**/*.wasm'],
  worker: { format: 'es' },
  server: {
    port,
    strictPort: true,
    watch: { ignored: (p: string) => skip.some((d) => p.startsWith(d)) },
  },
  preview: { port, strictPort: true },
  optimizeDeps: {
    // The scanner does not follow `new Worker(new URL(…))` from index.html, so the workers are entries too;
    // it must not crawl fixture HTML or worktrees. manifold-3d resolves its wasm with
    // `new URL('manifold.wasm', import.meta.url)`, which breaks under pre-bundling (§5.4).
    entries: ['index.html', 'src/workers/*.worker.ts'],
    exclude: ['manifold-3d'],
  },
  test: {
    // src/core runs in workers, so its tests run without a DOM; UI tests opt in per file with
    // `// @vitest-environment happy-dom`.
    environment: 'node',
    // Vitest 4 excludes only node_modules and .git by default. These are root-relative, so a run inside a
    // worktree still collects that worktree's own tests.
    exclude: [...configDefaults.exclude, '.claude/**', 'e2e/**'],
    setupFiles: ['./src/test/setup.ts'],
    // Eight agents share this machine: a cold or loaded run took heavy tests past vitest's 5 s default (design
    // v1.4, §6.1 rule 5). Heavy suites still name their own, longer timeouts.
    testTimeout: 30_000,
    hookTimeout: 30_000,
    // Tests that assert a wall-clock duration carry this tag (src/test/timing.ts, §6.1 rule 5): `npm test` checks
    // them against a loose sanity bound, `npm run perf` runs only them, serially, against the strict budget.
    // A test's own `retry`/`timeout` win over these.
    tags: [{ name: 'perf', description: 'wall-clock budget (§5.8, §6.1 rule 5): strict only under npm run perf', retry: 2, timeout: 180_000 }],
  },
});
