// Compile-time guard for the frozen signatures of DESIGN.md §5.2.1. Step 0 owned; no runtime code.
//
// Each line asserts that the function (or component) a module exports today has EXACTLY the frozen signature:
// identical parameter types (their names are free) and an identical result type. A Step 0 stub passes, and so
// does a real implementation written with the same types. An implementation that dropped an optional
// parameter, widened or narrowed a type, or is typed `any` makes `npm run typecheck` fail HERE — fix the
// implementation, or propose the change through the S0 amendment lane (§6.1 rule 7). Do not edit this file to
// make a track compile.
//
// `typeof import(…)` is a type query: nothing is imported at run time.
import type { ComponentType } from 'react';
import type * as E from '../entryPoints';
import type * as U from '../ui';

type Identical<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
type IsAny<T> = 0 extends 1 & T ? true : false;
type Fn = (...a: never[]) => unknown;

/** True when `Actual` is a function with the frozen parameter list and the frozen result type. */
type SameSignature<Actual, Frozen extends Fn> =
  IsAny<Actual> extends true
    ? false
    : Actual extends Fn
      ? Identical<Parameters<Actual>, Parameters<Frozen>> extends true
        ? Identical<ReturnType<Actual>, ReturnType<Frozen>>
        : false
      : false;

/** The props of a function, class, memo, forwardRef or lazy component. */
type PropsOf<C> = C extends (props: infer P) => unknown ? P : C extends new (props: infer P, ...rest: never[]) => unknown ? P : never;

/** True when `Actual` is a React component whose props are exactly `Props`. */
type SameProps<Actual, Props> = IsAny<Actual> extends true ? false : Identical<PropsOf<Actual>, Props>;

type Check<T extends true> = T;

// ---- Step 0 kernels. encodePng returns Uint8Array<ArrayBuffer>, a subtype of the frozen Uint8Array that can
//      also be handed to Blob and crypto.subtle; so its result is checked for assignability, not identity.
type EncodePng = typeof import('../../core/kernel/png').encodePng;
export type KernelEntryPoints = [
  Check<Identical<Parameters<EncodePng>, Parameters<E.EncodePngFn>>>,
  Check<ReturnType<EncodePng> extends ReturnType<E.EncodePngFn> ? true : false>,
  Check<SameSignature<typeof import('../../core/kernel/png').decodePng, E.DecodePngFn>>,
];

// ---- T1
export type T1EntryPoints = [
  Check<SameSignature<typeof import('../../core/image2d/run').runChart, E.RunChartFn>>,
  Check<SameSignature<typeof import('../../core/yarn/match').nearestYarn, E.NearestYarnFn>>,
];

// ---- T2
export type T2EntryPoints = [
  Check<SameSignature<typeof import('../../core/techniques/index').buildPattern2D, E.BuildPattern2DFn>>,
  Check<SameSignature<typeof import('../../core/pattern/render').renderLine, E.RenderLineFn>>,
  Check<SameSignature<typeof import('../../core/techniques/export').exportChart, E.ExportChartFn>>,
  Check<SameSignature<typeof import('../../core/pattern/text').renderPatternText, E.RenderPatternTextFn>>,
  Check<SameSignature<typeof import('../../core/pattern/skill').computeSkill, E.ComputeSkillFn>>,
  Check<SameSignature<typeof import('../../core/pattern/notes').notesFor, E.NotesForFn>>,
  Check<SameSignature<typeof import('../../core/pattern/terminology').abbreviationsFor, E.AbbreviationsForFn>>,
  Check<SameSignature<typeof import('../../core/pattern/terminology').specialStitchesFor, E.SpecialStitchesForFn>>,
  Check<SameProps<typeof import('../../ui/pattern/PatternView').PatternView, U.PatternViewProps>>,
  Check<SameProps<typeof import('../../ui/pattern/MaterialsView').MaterialsView, U.MaterialsViewProps>>,
];

// ---- T3
export type T3EntryPoints = [Check<SameSignature<typeof import('../../core/recon/fit').fitPart, E.FitPartFn>>];

// ---- T4
export type T4EntryPoints = [Check<SameSignature<typeof import('../../core/ami/generate').generateAmigurumi, E.GenerateAmigurumiFn>>];

// ---- T6
export type T6EntryPoints = [Check<SameSignature<typeof import('../../ui/shape/placement').renderPlacementImage, E.RenderPlacementImageFn>>];

// ---- T7
export type T7EntryPoints = [Check<SameSignature<typeof import('../../core/importer/index').importInputs, E.ImportInputsFn>>];

// ---- T8
export type T8EntryPoints = [
  Check<SameSignature<typeof import('../../core/persist/repo').createProjectRepository, E.CreateProjectRepositoryFn>>,
  Check<SameSignature<typeof import('../../ui/library/useAutosave').useAutosave, E.UseAutosaveFn>>,
  Check<SameSignature<typeof import('../../core/print/pdf').buildPdf, E.BuildPdfFn>>,
];

// ---- The guard itself must be able to fail. Every line below has to be a compile error; if one stops being
//      an error, `tsc` reports its unused @ts-expect-error.
type Run = E.RunChartFn;
type Req = Parameters<Run>[0];
type Res = ReturnType<Run>;
type Gate = Parameters<Run>[1];
export type GuardSelfTests = [
  Check<SameSignature<Run, Run>>,
  Check<SameSignature<Run & { __stub: true }, Run>>,
  Check<SameSignature<(renamed: Req, alsoRenamed?: Gate) => Res, Run>>,
  // @ts-expect-error an implementation typed `any` is not a frozen signature
  Check<SameSignature<any, Run>>,
  // @ts-expect-error neither is a function that accepts and returns anything
  Check<SameSignature<(...a: any[]) => any, Run>>,
  // @ts-expect-error a dropped optional parameter breaks the callers that pass it
  Check<SameSignature<(req: Req) => Res, Run>>,
  // @ts-expect-error an optional parameter that became required
  Check<SameSignature<(req: Req, gate: NonNullable<Gate>) => Res, Run>>,
  // @ts-expect-error an extra parameter
  Check<SameSignature<(req: Req, gate?: Gate, verbose?: boolean) => Res, Run>>,
  // @ts-expect-error a function that never returns
  Check<SameSignature<(req: Req, gate?: Gate) => never, Run>>,
  // @ts-expect-error a wider result
  Check<SameSignature<(req: Req, gate?: Gate) => Res | undefined, Run>>,
  // @ts-expect-error a narrower result
  Check<SameSignature<(req: Req, gate?: Gate) => Promise<Awaited<Res> & { extra: number }>, Run>>,
  // @ts-expect-error a narrower property inside the result
  Check<SameSignature<() => { status: 'saved'; flush(): Promise<void> }, E.UseAutosaveFn>>,
  // @ts-expect-error a value that is not a function
  Check<SameSignature<{ __stub: true }, Run>>,
  // @ts-expect-error a component with other props
  Check<SameProps<ComponentType<{ doc: string }>, U.PatternViewProps>>,
  // @ts-expect-error a component typed `any`
  Check<SameProps<any, U.PatternViewProps>>,
  // @ts-expect-error a component with one prop missing
  Check<SameProps<(props: Omit<U.PatternViewProps, 'highlight'>) => null, U.PatternViewProps>>,
  Check<SameProps<(props: U.PatternViewProps) => null, U.PatternViewProps>>,
  Check<SameProps<ComponentType<U.MaterialsViewProps>, U.MaterialsViewProps>>,
];
