// fixtures/models/** is generated by the Step 0 kernels: this file regenerates each fixture and compares it with
// the committed bytes (DESIGN.md §6.2 item 6). After an intended change, rewrite the files with
//   UPDATE_FIXTURES=1 npm test -- src/core/model/__tests__/fixtures.test.ts
// and review the diff: track T7's importer must reproduce teddy.canonical.json exactly (golden G12).
import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import type { CrochetModelV1, Part } from '../../../types/model';
import { attachGraph, isOneTree } from '../attach';
import { overlapAlongRay } from '../place';
import { crochetModelSchema, stringifyModel } from '../schema';
import { boundsSize, modelBounds } from '../transforms';
import { buildEveryType, buildEveryTypeMeshes, EVERY_TYPE_MESH_REF, meshFromJson, readEveryTypeMeshes, stringifyMeshes } from './helpers/everyType';
import { buildCanonicalTeddy, CANONICAL_TEDDY_URL, EVERY_TYPE_MESH_URL, EVERY_TYPE_URL, readObservedTeddy } from './helpers/teddy';

const UPDATE = process.env.UPDATE_FIXTURES === '1';

function expectFile(url: URL, text: string): void {
  if (UPDATE) writeFileSync(url, text);
  expect(readFileSync(url, 'utf8')).toBe(text);
}

const byId = (m: CrochetModelV1): Record<string, Part> => Object.fromEntries(m.parts.map((p) => [p.id, p]));

describe('fixtures/models/teddy.canonical.json', () => {
  const teddy = buildCanonicalTeddy();

  it('is reproduced byte for byte from the observed Claude Design teddy (§6.2 item 6, G12)', () => {
    expectFile(CANONICAL_TEDDY_URL, stringifyModel(teddy.model));
  });

  it('the generator is deterministic', () => {
    expect(stringifyModel(buildCanonicalTeddy().model)).toBe(stringifyModel(teddy.model));
  });

  it('§3.7.3 golden: dialect normalization, before grounding (±1e-3)', () => {
    const p = byId(teddy.normalized);
    const close = (actual: readonly number[] | undefined, expected: number[]): void => {
      expect(actual).toBeDefined();
      (actual as number[]).forEach((v, i) => expect(Math.abs(v - expected[i])).toBeLessThanOrEqual(1e-3));
    };
    close(p.muzzle.position, [0, 6.6, 1.9]);
    close(p.nose.position, [0, 6.9, 2.42]);
    close(p.eye_l.position, [0.78, 7.45, 2.02]);
    close(p.ear_l.position, [1.6, 8.95, -0.1]);
    close(p.ear_l.rotationDeg, [0, 0, -28]);
    close(p.ear_l_inner.position, [1.5765, 8.9059, 0.16]);
    close(p.ear_l_inner.rotationDeg, [0, 0, -28]);
    close(p.foot_pad_l.position, [1.4411, 0.9706, 2.6061]);
    close(p.foot_pad_l.rotationDeg, [82, 0, -12]);
    expect(p.leg_l.type === 'capsule' && p.leg_l.dims.length).toBeCloseTo(3.1, 9);
    // eye_l from the head center: azimuth 22.1°, elevation 6.9°
    const d = [0, 1, 2].map((i) => p.eye_l.position[i] - p.head.position[i]);
    expect((Math.atan2(d[0], d[2]) * 180) / Math.PI).toBeCloseTo(22.1, 1);
    expect((Math.asin(d[1] / Math.hypot(d[0], d[1], d[2])) * 180) / Math.PI).toBeCloseTo(6.9, 1);
  });

  it('§3.7.3 dialect table: canonical dims, palette array, color ids, labels, eyes, header defaults, notes', () => {
    const raw = readObservedTeddy();
    const m = teddy.model;
    expect(m.parts.map((p) => p.id)).toEqual(raw.parts.map((p) => p.id));
    expect(m.parts).toHaveLength(17);
    expect(m.palette).toEqual([
      { id: 'caramel_yarn', hex: '#B07A4A', name: 'caramel_yarn' },
      { id: 'cream_yarn', hex: '#F2E3C6', name: 'cream_yarn' },
      { id: 'dark_brown_yarn', hex: '#3B2A20', name: 'dark_brown_yarn' },
      { id: 'black_safety_eye', hex: '#111111', name: 'black_safety_eye' },
    ]);
    const p = byId(m);
    expect(p.arm_l.dims).toEqual({ r: 0.55, length: 3 }); // 1.9 straight + 2 × 0.55
    expect(p.leg_l.dims).toEqual({ r: 0.75, length: 3.1 });
    expect(p.body.label).toBe('Body');
    expect(p.body.color).toBe('caramel_yarn');
    expect(p.nose.color).toBe('dark_brown_yarn');
    expect(p.eye_l.crochet).toEqual({ make: 'safety_eye' });
    expect(p.eye_r.crochet).toEqual({ make: 'safety_eye' });
    expect(m.parts.filter((x) => x.crochet).map((x) => x.id)).toEqual(['eye_l', 'eye_r']);
    expect(m.axes).toEqual({ up: '+Y', front: '+Z', left: '+X' });
    expect(m.revision).toBe(0);
    expect(m.source).toEqual({ tool: 'claude-design', stage: 'refined' });
    expect(m.assumptions).toEqual([raw.notes]);
    expect(Object.keys(m)).not.toContain('notes');
    expect(teddy.repairs.filter((r) => r.code === 'unknown-key')).toHaveLength(1);
  });

  it('§3.7.3 / §3.7.6: grounding shifts every part by +0.0789; the measured height 9.88 is recorded', () => {
    expect(teddy.groundDy).toBeCloseTo(0.0789, 4);
    expect(teddy.measuredHeight).toBeCloseTo(9.8789, 4);
    expect(teddy.model.finishedSize).toEqual({ height: 9.878905 });
    const before = byId(teddy.normalized);
    for (const part of teddy.model.parts) {
      expect(part.position[1] - before[part.id].position[1]).toBeCloseTo(teddy.groundDy, 6);
      expect(part.position[0]).toBeCloseTo(before[part.id].position[0], 6);
    }
    const b = modelBounds(teddy.model);
    expect(Math.abs(b.min[1])).toBeLessThanOrEqual(1e-6);
    // research 08, measured on the exported OBJ: x ±2.906, height 9.88, z −2.25 … 2.82
    expect(b.max[0]).toBeCloseTo(2.906, 3);
    expect(b.min[0]).toBeCloseTo(-2.906, 3);
    expect(b.min[2]).toBeCloseTo(-2.25, 3);
    expect(b.max[2]).toBeCloseTo(2.82, 3);
  });

  it('§3.7.3 golden: one tree rooted at body, the mirror pairs, and it validates', () => {
    const m = teddy.model;
    expect(isOneTree(m)).toBe(true);
    const parents = Object.fromEntries(m.parts.map((p) => [p.id, p.attach?.to ?? null]));
    expect(parents).toEqual({
      body: null,
      head: 'body',
      muzzle: 'head',
      nose: 'muzzle',
      eye_l: 'head',
      eye_r: 'head',
      ear_l: 'head',
      ear_l_inner: 'ear_l',
      ear_r: 'head',
      ear_r_inner: 'ear_r',
      arm_l: 'body',
      arm_r: 'body',
      leg_l: 'body',
      foot_pad_l: 'leg_l',
      leg_r: 'body',
      foot_pad_r: 'leg_r',
      tail: 'body',
    });
    const mirrors = Object.fromEntries(m.parts.filter((p) => p.mirrorOf).map((p) => [p.id, p.mirrorOf]));
    expect(mirrors).toEqual({
      eye_r: 'eye_l',
      ear_r: 'ear_l',
      ear_r_inner: 'ear_l_inner',
      arm_r: 'arm_l',
      leg_r: 'leg_l',
      foot_pad_r: 'foot_pad_l',
    });
    expect(teddy.repairs.filter((r) => r.code === 'attach-inferred')).toHaveLength(6);
    expect(teddy.repairs.filter((r) => r.code === 'mirror-inferred')).toHaveLength(6);
    expect(crochetModelSchema.parse(m)).toEqual(m);
  });

  it('every number in the file is rounded to 1e-6 and no −0 is written', () => {
    const text = stringifyModel(teddy.model);
    expect(text).not.toMatch(/-0[,\]\s]/);
    for (const match of text.matchAll(/-?\d+\.\d+/g)) expect(match[0].split('.')[1].length).toBeLessThanOrEqual(6);
    expect(text.endsWith('}\n')).toBe(true);
  });
});

describe('fixtures/models/every-type.json', () => {
  const model = buildEveryType();
  const meshes = buildEveryTypeMeshes();

  it('is reproduced byte for byte by its generator, with its mesh buffers', () => {
    expectFile(EVERY_TYPE_URL, stringifyModel(model));
    expectFile(EVERY_TYPE_MESH_URL, stringifyMeshes(meshes));
  });

  it('holds one part of every type, every flat shape, every region kind and every feature kind, and x-* keys', () => {
    expect(new Set(model.parts.map((p) => p.type))).toEqual(
      new Set(['sphere', 'ellipsoid', 'capsule', 'cylinder', 'cone', 'torus', 'lathe', 'flat', 'box', 'mesh']),
    );
    const flats = model.parts.flatMap((p) => (p.type === 'flat' ? [p.dims.shape] : []));
    expect(new Set(flats)).toEqual(new Set(['circle', 'oval', 'teardrop', 'triangle', 'rect', 'polygon']));
    const regions = model.parts.flatMap((p) => p.regions ?? []).map((r) => r.kind);
    expect(new Set(regions)).toEqual(new Set(['band', 'stripes', 'patch', 'spot', 'pattern']));
    expect(new Set((model.features ?? []).map((f) => f.kind))).toEqual(
      new Set(['safety_eye', 'embroidered_eye', 'felt', 'nose', 'mouth', 'cheek', 'brow', 'whiskers', 'line', 'applique']),
    );
    expect(new Set(model.parts.map((p) => p.attach?.method).filter(Boolean))).toEqual(
      new Set(['sewn', 'crochet-in-place', 'worked-from', 'glued', 'none']),
    );
    expect(new Set(model.parts.map((p) => p.attach?.openEnd).filter(Boolean))).toEqual(new Set(['top', 'bottom', 'none']));
    expect(new Set(model.parts.map((p) => p.stuffing).filter(Boolean))).toEqual(new Set(['firm', 'medium', 'light', 'none']));
    expect(new Set(model.parts.map((p) => p.crochet?.make).filter(Boolean))).toEqual(
      new Set(['auto', 'piece', 'applique', 'embroidery', 'region', 'skip']),
    );
    expect(model['x-cpg']).toEqual({ project: 'every-type', seedRev: 0 });
    expect(model.parts.some((p) => Object.keys(p).some((k) => k.startsWith('x-')))).toBe(true);
    expect(model.parts.some((p) => p.paint?.kind === 'uv64')).toBe(true);
    expect(model.parts.filter((p) => p.type === 'torus').map((p) => p.type === 'torus' && (p.dims.arcDeg ?? 360))).toEqual([360, 200]);
  });

  it('is a valid, grounded model with one attach tree; every child enters its parent by 0.10 in along its stacking ray', () => {
    expect(crochetModelSchema.parse(model)).toEqual(model);
    expect(isOneTree(model)).toBe(true);
    const buffers = readEveryTypeMeshes();
    const bounds = modelBounds(model, buffers);
    expect(Math.abs(bounds.min[1])).toBeLessThanOrEqual(1e-6);
    const size = boundsSize(bounds);
    expect(model.finishedSize.height).toBeCloseTo(size[1], 5);
    expect(model.finishedSize.width).toBeCloseTo(size[0], 5);
    expect(model.finishedSize.depth).toBeCloseTo(size[2], 5);
    const g = attachGraph(model.parts);
    model.parts.forEach((p, i) => {
      const parent = g.parent[i];
      if (parent === null) return;
      // The fixture was stacked with the kernel's default surfaces (a mesh part = its inscribed ellipsoid).
      expect(overlapAlongRay(model.parts[parent], p), p.id).toBeCloseTo(0.1, 4);
    });
  });

  it('the mesh buffer matches its part: bounding box = bboxIn, centered on the origin, closed and outward', () => {
    const blob = model.parts.find((p) => p.type === 'mesh');
    expect(blob?.type === 'mesh' && blob.dims.meshRef).toBe(EVERY_TYPE_MESH_REF);
    const mesh = meshFromJson(meshes[EVERY_TYPE_MESH_REF]);
    const min = [Infinity, Infinity, Infinity];
    const max = [-Infinity, -Infinity, -Infinity];
    for (let i = 0; i < mesh.positions.length; i += 3) {
      for (let k = 0; k < 3; k++) {
        min[k] = Math.min(min[k], mesh.positions[i + k]);
        max[k] = Math.max(max[k], mesh.positions[i + k]);
      }
    }
    if (blob?.type !== 'mesh') throw new Error('no mesh part');
    for (let k = 0; k < 3; k++) {
      expect(max[k] - min[k]).toBeCloseTo(blob.dims.bboxIn[k], 5);
      expect(max[k] + min[k]).toBeCloseTo(0, 5);
    }
    expect(mesh.labels).toHaveLength(mesh.positions.length / 3);
    // Every edge is shared by exactly two triangles, in opposite directions: closed and consistently wound.
    const edges = new Map<string, number>();
    for (let k = 0; k < mesh.indices.length; k += 3) {
      for (let e = 0; e < 3; e++) {
        const a = mesh.indices[k + e];
        const b = mesh.indices[k + ((e + 1) % 3)];
        edges.set(`${a}>${b}`, (edges.get(`${a}>${b}`) ?? 0) + 1);
      }
    }
    for (const [key, count] of edges) {
      const [a, b] = key.split('>');
      expect(count).toBe(1);
      expect(edges.get(`${b}>${a}`)).toBe(1);
    }
  });
});
