// T4.1 goldens (DESIGN.md §2.13 G5, G6, G7, G19, G20 at count level; §2.10.5, §2.10.6, §2.10.8).
//
// The golden file `golden/t41-counts.json` is generated by the implementation (never typed by hand); this suite
// (1) regenerates it and compares it byte for byte with the committed file — after an intended change rewrite it
// with `UPDATE_GOLDEN=1 npm test -- src/core/ami/__tests__/goldens.test.ts` and review the diff — and (2) compares
// every list in it with the lists read from DESIGN.md's own text (helpers/spec.ts).
import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { sewingTail } from '../poles';
import { generateGoldens, stringifyGoldens, worsted } from './helpers/goldens';
import { spec } from './helpers/spec';

const FILE = new URL('./golden/t41-counts.json', import.meta.url);
const UPDATE = process.env.UPDATE_GOLDEN === '1';

const goldens = generateGoldens();
const text = stringifyGoldens(goldens);
if (UPDATE) writeFileSync(FILE, text);
const committed = JSON.parse(readFileSync(FILE, 'utf8')) as ReturnType<typeof generateGoldens>;

describe('golden file', () => {
  it('is reproduced byte for byte by the implementation', () => {
    expect(readFileSync(FILE, 'utf8')).toBe(text);
  });

  it('is deterministic', () => {
    expect(stringifyGoldens(generateGoldens())).toBe(text);
  });
});

describe('G5 — textbook sphere k = 6 (§2.10.5, §2.10.8)', () => {
  const s = spec.textbookSphere();
  const g = committed['G5-textbook-sphere'];

  it('w/h = 1.0: the 17-round list', () => {
    expect(g.generator).toBe('textbook');
    expect(g.counts).toEqual(s.counts);
    expect(g.rounds).toBe(s.rounds);
    expect(g.start).toEqual({ k: 'mr', n: 6 });
    expect(g.finish).toMatchObject({ kind: 'gather', tailIn: 6 });
  });

  it('the counts of the §2.10.8 golden text', () => {
    expect(g.counts).toEqual(spec.textbookTextCounts());
  });

  it('worsted defaults (w/h = 1.05): 7 plain rounds, 18 rounds', () => {
    const w = committed['G5-textbook-sphere-worsted'];
    expect(w.rounds).toBe(s.worstedRounds);
    const peak = Math.max(...w.counts);
    expect(peak).toBe(36);
    // the plain rounds are the 6k rounds after the increase round
    expect(w.counts.filter((c) => c === peak).length - 1).toBe(s.worstedPlain);
  });
});

describe('G6 — lathe semicircle r = 1.5 (§2.10.5)', () => {
  const s = spec.latheSemicircle();

  it('exact', () => {
    const g = committed['G6-lathe-semicircle-exact'];
    expect(g.N).toBe(s.N);
    expect(g.rounds).toBe(s.rounds);
    expect(g.symmetric).toBe(true);
    expect(g.counts).toEqual(s.exact);
  });

  it('classic (batched, p0 = 6)', () => {
    const g = committed['G6-lathe-semicircle-classic'];
    expect(g.generator).toBe('pathA');
    expect(g.N).toBe(s.N);
    expect(g.counts).toEqual(s.classic);
  });

  it('the analytic semicircle (a sphere, exact) gives the same list', () => {
    expect(committed['G6-sphere-exact'].counts).toEqual(s.exact);
  });
});

describe('G7 — cone, horn, closed cylinder (§2.10.5)', () => {
  it('cone classic: 6 6 6 6 12 … (classic MR = 6, batchCounts p0 = 6)', () => {
    const s = spec.cone();
    const g = committed['G7-cone-classic'];
    expect(g.N).toBe(s.N);
    expect(g.counts).toEqual(s.classic);
    expect(g.ideal.slice(0, s.idealsHead.length).map((x) => Math.round(x * 100) / 100)).toEqual(s.idealsHead);
    expect(Math.round(g.ideal[g.ideal.length - 1] * 100) / 100).toBe(s.idealLast);
    expect(g.start).toEqual({ k: 'mr', n: 6 });
    expect(g.finish).toMatchObject({ kind: 'open' });
  });

  it('cone exact: hysteresis 2 4 6 8 …, then the pole rule sets n₁ = 5 and lifts n₂ to 5', () => {
    const s = spec.cone();
    const g = committed['G7-cone-exact'];
    expect(g.raw.slice(0, s.hysteresisHead.length)).toEqual(s.hysteresisHead);
    expect(g.counts).toEqual(s.exact);
  });

  it('horn: exact list, raw tail … 6 4 2 → … 6 5 5 → trailing duplicate dropped, BLO on Rnd 4', () => {
    const s = spec.horn();
    const g = committed['G7-horn'];
    expect(g.counts).toEqual(s.exact);
    expect(g.raw.slice(-s.rawTail.length)).toEqual(s.rawTail);
    expect(g.dropped).toBe(1);
    expect([...g.counts, g.counts[g.counts.length - 1]].slice(-s.clampedTail.length)).toEqual(s.clampedTail);
    expect(g.blo).toEqual([s.bloRound]);
    expect(g.finish).toMatchObject({ kind: 'gather' });
  });

  it('closed cylinder ⌀1.5 × 2: 17 rounds, BLO on rounds 5 and 15 (exact and classic)', () => {
    const s = spec.cylinder();
    for (const id of ['G7-cylinder-exact', 'G7-cylinder-classic'] as const) {
      const g = committed[id];
      expect(g.counts, id).toEqual(s.counts);
      expect(g.rounds, id).toBe(s.rounds);
      expect(g.blo, id).toEqual(s.blo);
      expect(g.flo, id).toEqual([]);
    }
  });
});

describe('G19 — ovals (§2.10.5)', () => {
  it('box w 2, d 1, h 1.5: S = 5, ch 8, the closed-oval list, BLO on Rnds 4 and 11, flatten across 8 sc', () => {
    const s = spec.closedOvalBox();
    const g = committed['G19-box-closed-oval'];
    expect(g.ovalS).toEqual(Array<number>(s.rounds).fill(s.S));
    expect(g.start).toEqual({ k: 'chainOval', chains: s.chains });
    expect(g.counts).toEqual(s.counts);
    expect(g.N).toBe(s.N);
    expect(g.rounds).toBe(s.rounds);
    expect(g.blo).toEqual(s.blo);
    expect(g.finish).toMatchObject({ kind: 'flattenSc' });
    expect((g.finish as { text: string }).text).toContain(`sc across (${s.finishSc} sc)`);
  });

  it('oval ellipsoid rx 1.2, ry 0.6, rz 2.0: S_k, ch 5, counts, circular part, mirrored ideals, finish across 5 sts', () => {
    const s = spec.ovalEllipsoid();
    const g = committed['G19-oval-ellipsoid'];
    expect(g.N).toBe(s.N);
    expect(g.rounds).toBe(s.rounds);
    expect(g.symmetric).toBe(true);
    expect(g.ovalS).toEqual(s.S);
    expect(Math.max(...(g.ovalS as number[]))).toBe(s.sMax);
    expect(g.ideal.slice(0, s.idealsHead.length).map((x) => Math.round(x * 100) / 100)).toEqual(s.idealsHead);
    expect(g.start).toEqual({ k: 'chainOval', chains: s.chains });
    expect(g.counts).toEqual(s.counts);
    expect(g.circ).toEqual(s.circ);
    expect((g.finish as { text: string }).text).toContain(`(${s.finishSts} sts each)`);
  });
});

describe('G20 — open capsule, the §3.6 arm_l (§2.10.5, §2.10.6)', () => {
  const s = spec.openCapsule();

  it('worsted light gauge is the spec’s wS 0.195, hS 0.186', () => {
    const w = worsted('light');
    expect(Math.round(w.wS * 1000) / 1000).toBe(s.wS);
    expect(Math.round(w.hS * 1000) / 1000).toBe(s.hS);
  });

  it('6 12 12×5, open with 12 sts, a 14" (35 cm) tail', () => {
    const g = committed['G20-open-capsule'];
    expect(g.generator).toBe('textbook');
    expect(Math.round(g.L * 1000) / 1000).toBe(s.sEnd);
    expect(g.rounds).toBe(s.rEnd);
    expect(g.counts).toEqual(s.counts);
    expect(g.counts[g.counts.length - 1]).toBe(s.openSts);
    expect(g.finish).toMatchObject({ kind: 'open', tailIn: s.tailIn });
    expect((g.finish as { text: string }).text).toBe(`Fasten off, leaving a ${s.tailIn}" (${s.tailCm} cm) tail for sewing.`);
  });

  it('the closed textbook capsule would be 6 12 12×6 6', () => {
    expect(committed['G20-closed-capsule'].counts).toEqual(s.closed);
  });
});

describe('§2.10.6 sewing-tail examples', () => {
  it('12-st arm opening → 14" (35 cm) at the light gauge; 36-st opening → 30" (75 cm) at the firm gauge', () => {
    const [arm, big] = spec.tailExamples();
    const t1 = sewingTail(arm.sts * worsted('light').wS);
    expect([t1.in, t1.cm]).toEqual([arm.in, arm.cm]);
    const t2 = sewingTail(big.sts * worsted('firm').wS);
    expect([t2.in, t2.cm]).toEqual([big.in, big.cm]);
  });
});
