// T4.2 goldens (DESIGN.md §2.13 G5, G7, G8, G19 and the teddy muzzle at text level; §2.10.5, §2.10.6, §2.10.8,
// §2.10.11): counts → placement → fold → T2's renderLine (docKind '3d') → validate3d.
//
// The golden file `golden/t42-text.json` is generated by the implementation (never typed by hand): this suite
// regenerates it and compares it byte for byte with the committed file (rewrite with `UPDATE_GOLDEN=1 npm test --
// src/core/ami/__tests__/text.test.ts` and review the diff), then compares the text with the sentences read from
// DESIGN.md and research 07 (helpers/spec.ts).
import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import type { Issue } from '../../../types/issues';
import { expand } from '../../pattern/ops';
import { canonicalCompact, encodeOps } from '../../pattern/encode';
import { renderLine } from '../../pattern/render';
import { placePiece } from '../place';
import { profileOf } from '../profiles';
import { pieceText } from '../text3d';
import { buildPiece, generateTextGoldens, MUZZLE, stringifyTextGoldens, textCases, type BuiltPiece } from './helpers/pieces';
import { worsted } from './helpers/goldens';
import { parseOps } from './helpers/ops';
import { researchOval, spec } from './helpers/spec';

const FILE = new URL('./golden/t42-text.json', import.meta.url);
const UPDATE = process.env.UPDATE_GOLDEN === '1';
const generated = stringifyTextGoldens(generateTextGoldens());
if (UPDATE) writeFileSync(FILE, generated);

const built = new Map<string, BuiltPiece>(textCases().map((c) => [c.id, c.build()]));
const piece = (id: string) => {
  const b = built.get(id);
  if (!b) throw new Error(`no case ${id}`);
  return b;
};
const errors = (issues: readonly Issue[]) => issues.filter((i) => i.severity === 'error');
const codes = (issues: readonly Issue[]) => issues.map((i) => i.code);
const MUZZLE_PART = MUZZLE;
const MUZZLE_L = profileOf(MUZZLE, { axis: 'z', start: 'top' })?.L as number;

describe('golden file t42-text.json', () => {
  it('is reproduced byte for byte by the implementation', () => {
    expect(readFileSync(FILE, 'utf8')).toBe(generated);
  });
  it('is deterministic', () => {
    expect(stringifyTextGoldens(generateTextGoldens())).toBe(generated);
  });
  it('no golden piece has an E_* issue', () => {
    for (const [id, b] of built) expect(errors(b.issues), id).toEqual([]);
  });
});

describe('G5 — textbook sphere k = 6, exact text (§2.10.8)', () => {
  it('w/h = 1.0: every line equals the spec text', () => {
    expect(piece('G5-textbook-sphere').text).toEqual(spec.textbookText());
  });

  it('worsted (w/h 1.05): the same text with 7 plain rounds (Rnds 7–13)', () => {
    const want = spec.textbookText().flatMap((l) => {
      const m = l.match(/^Rnds 7–12 \(6 rnds\): (.*)$/);
      if (m) return [`Rnds 7–13 (7 rnds): ${m[1]}`];
      const r = l.match(/^Rnd (\d+): (.*)$/);
      return r && Number(r[1]) >= 13 ? [`Rnd ${Number(r[1]) + 1}: ${r[2]}`] : [l];
    });
    expect(spec.textbookSphere().worstedPlain).toBe(7);
    expect(piece('G5-textbook-sphere-worsted').text).toEqual(want);
  });

  it('raises no W_STACKED (nor any other issue)', () => {
    expect(spec.g5NoStacked()).toBe(true);
    expect(codes(piece('G5-textbook-sphere').issues)).toEqual([]);
    expect(codes(piece('G5-textbook-sphere-worsted').issues)).toEqual([]);
  });

  it('every printed line is the encoder’s form of the placed ops (the text is the line)', () => {
    for (const line of piece('G5-textbook-sphere').lines) {
      expect(expand(encodeOps(line.ops))).toEqual(line.ops);
    }
  });
});

describe('G7 — closed cylinder ⌀1.5 × 2: Rnds 4, 5, 14, 15 (jogless prep, BLO sc2tog; §2.10.5)', () => {
  const want = spec.cylinderText();
  for (const id of ['G7-cylinder-exact', 'G7-cylinder-classic']) {
    it(`${id}: the spec lines appear exactly, in order`, () => {
      const text = piece(id).text;
      const at = text.indexOf(want.lines[0]);
      expect(at, text.join('\n')).toBeGreaterThan(0);
      expect(text.slice(at, at + want.lines.length)).toEqual(want.lines);
    });

    it(`${id}: Rnd 4's ops are the spec's (sc, inc, sc) × 5, sc, inc, sl st`, () => {
      const rnd4 = piece(id).lines.find((l) => l.n === 4);
      expect(rnd4?.ops).toEqual(parseOps(want.rnd4Ops));
      // and the encoder prints their shortest form, as the spec says
      expect(canonicalCompact(encodeOps(rnd4?.ops ?? []))).toBe(want.lines[0].replace(/^Rnd 4: /, '').replace(/ \(24\)$/, ''));
    });

    it(`${id}: no issue`, () => {
      expect(codes(piece(id).issues)).toEqual([]);
    });
  }
});

describe('G7 — horn: BLO on Rnd 4 with BLO sc2tog, jogless prep on Rnd 3 (§2.10.5)', () => {
  const b = piece('G7-horn');
  it('Rnd 3 ends with the jogless sl st; Rnd 4 is BLO with sc2tog in a repeat', () => {
    const r3 = b.text.find((l) => l.startsWith('Rnd 3:')) as string;
    const r4 = b.text.find((l) => l.startsWith('Rnd 4:')) as string;
    expect(r3).toMatch(/, sl st \(\d+\)$/);
    // the spec writes it `BLO (…, sc2tog) …`: a repeat in back loops whose decreases print as sc2tog
    expect(spec.hornBloText()).toMatch(/^BLO \(…, sc2tog\) …$/);
    expect(r4).toMatch(/^Rnd 4: BLO \([^)]*sc2tog[^)]*\) x \d+/);
    expect(r4).not.toMatch(/\bdec\b/);
    expect(codes(b.issues)).toEqual([]);
  });
});

describe('G8 — oval ch 10 (§2.13 G8, §2.10.6, research 07 §6.9)', () => {
  const g8 = spec.g8();
  const r07 = researchOval();
  const b = piece('G8-oval-ch10');

  it('ch 10 ⇒ S = 7; counts 20, 26, 32', () => {
    expect(g8.chains).toBe(10);
    expect(g8.S).toBe(7);
    expect(b.lines.map((l) => l.stated)).toEqual(g8.counts);
  });

  it('Rnd 1 is the §2.10.6 chain-oval sentence after "Ch 10." (research 07 §6.9)', () => {
    expect(b.text[0]).toBe(`${r07.chain} ${r07.rnd1}`);
  });

  it('Rnd 2 prints exactly as §2.13 G8 (the `N op` form)', () => {
    expect(b.text[1]).toBe(g8.rnd2);
  });

  it('Rnd 3 is the segment-preserving text of research 07 §6.9', () => {
    expect(b.text[2]).toBe(r07.rnd3);
  });

  it('no E_*, no W_SPACING / W_STAGGER / W_STACKED', () => {
    expect(codes(b.issues)).toEqual([]);
  });
});

describe('G19 — box closed oval and oval ellipsoid (§2.10.5)', () => {
  it('box: jogless prep before Rnds 4 and 11; Rnd 11 is a BLO sc2tog round', () => {
    const box = spec.closedOvalBox();
    const b = piece('G19-box-closed-oval');
    for (const r of box.blo) {
      const before = b.lines.find((l) => (l.nEnd ?? l.n) === r - 1);
      expect(before?.ops.at(-1), `Rnd ${r - 1}`).toEqual({ k: 'st', st: 'slst' });
      expect(b.text.find((l) => l.startsWith(`Rnd ${r}:`))).toMatch(new RegExp(`^Rnd ${r}: BLO `));
    }
    const sc2tog = b.text.find((l) => l.startsWith(`Rnd ${spec.boxSc2togRound()}:`)) as string;
    expect(sc2tog).toMatch(/^Rnd \d+: BLO .*sc2tog/);
    expect(sc2tog).not.toMatch(/\bdec\b/);
  });

  it('box: the first round is the ch-8 chain oval, segment hints on every shaped round', () => {
    const b = piece('G19-box-closed-oval');
    expect(b.text[0]).toMatch(/^Ch 8\. Rnd 1: sc in 2nd ch from hook, sc in next 5 ch, 3 sc in last ch; working along the other side of the chain, sc in next 5 ch, 2 sc in last ch \(16\)$/);
    for (const l of b.unfolded.slice(1)) {
      if (l.ops.some((o) => o.k === 'inc' || o.k === 'dec')) expect(l.segments, `Rnd ${l.n}`).toBeDefined();
    }
  });

  for (const id of ['G19-box-closed-oval', 'G19-oval-ellipsoid']) {
    it(`${id}: every E_* passes; no W_SPACING / W_STAGGER / W_STACKED`, () => {
      const b = piece(id);
      expect(errors(b.issues)).toEqual([]);
      expect(codes(b.issues).filter((c) => c === 'W_SPACING' || c === 'W_STAGGER' || c === 'W_STACKED')).toEqual([]);
    });
  }

  it('oval ellipsoid: ch 5 start and the stated counts of the spec', () => {
    const e = spec.ovalEllipsoid();
    const b = piece('G19-oval-ellipsoid');
    expect(b.text[0]).toMatch(new RegExp(`^Ch ${e.chains}\\. Rnd 1: `));
    expect(b.unfolded.map((l) => l.stated)).toEqual(e.counts);
  });
});

describe('teddy muzzle (oval rx/ry = 1.33, axis Z, from its front tip, light; §2.10.1, §2.13)', () => {
  for (const id of ['teddy-muzzle-classic-closed', 'teddy-muzzle-classic-trimmed-46pct', 'teddy-muzzle-exact-closed', 'teddy-muzzle-exact-trimmed-46pct']) {
    it(`${id}: every E_* passes; no W_SPACING / W_STAGGER / W_STACKED`, () => {
      const b = piece(id);
      expect(b.counts.ovalS, 'an oval piece').toBeDefined();
      expect(errors(b.issues)).toEqual([]);
      expect(codes(b.issues).filter((c) => c === 'W_SPACING' || c === 'W_STAGGER' || c === 'W_STACKED')).toEqual([]);
    });
  }

  it('any trim from 30% to 90% of the profile: no E_*, no end-segment W_*', () => {
    const light = worsted('light');
    for (const style of ['classic', 'exact'] as const) {
      for (let f = 0.3; f <= 0.9 + 1e-9; f += 0.02) {
        const b = buildPiece('muzzle', MUZZLE_PART, { ...light, style, axis: 'z', start: 'top', trimAt: f * MUZZLE_L });
        expect(errors(b.issues), `${style} ${f}`).toEqual([]);
        expect(codes(b.issues).filter((c) => c === 'W_SPACING' || c === 'W_STAGGER' || c === 'W_STACKED'), `${style} ${f}`).toEqual([]);
      }
    }
  });
});

describe('G20 open capsule and the textbook pieces print through renderLine', () => {
  it('arm_l: 6 12 12×5, open (no decrease phase)', () => {
    const b = piece('G20-open-capsule');
    expect(b.text).toEqual(['Rnd 1: 6 sc in MR (6)', 'Rnd 2: inc in each st around (12)', 'Rnds 3–7 (5 rnds): sc in each st around (12)']);
    expect(codes(b.issues)).toEqual([]);
  });
});

describe('text goes through T2’s renderLine with docKind 3d (integration task T4-2)', () => {
  it('pieceText = renderLine(line, { …, docKind: "3d" }) for every line, in both dialects and terms', () => {
    const b = piece('G19-box-closed-oval');
    for (const dialect of ['compact', 'verbose'] as const) {
      for (const terms of ['us', 'uk'] as const) {
        const text = pieceText(b.lines, { dialect, terms, hand: 'right' });
        const rounds = text.filter((l) => /^(Ch \d+\. )?Rnds? \d/.test(l));
        expect(rounds.length).toBe(b.lines.length);
        b.lines.forEach((line, i) => expect(rounds[i].endsWith(renderLine(line, { dialect, terms, hand: 'right', docKind: '3d' }))).toBe(true));
      }
    }
  });

  it('an amigurumi round prints the amigurumi way even with a side tag (docKind is passed, not inferred)', () => {
    const line = { ...piece('G5-textbook-sphere').lines[2], side: 'RS' as const };
    expect(pieceText([line], { dialect: 'compact', terms: 'us', hand: 'right' })[0]).toBe(renderLine(line, { dialect: 'compact', terms: 'us', hand: 'right', docKind: '3d' }));
    expect(renderLine(line, { dialect: 'compact', terms: 'us', hand: 'right' })).not.toBe(renderLine(line, { dialect: 'compact', terms: 'us', hand: 'right', docKind: '3d' }));
  });

  it('UK terms rename the stitches (sc → dc) and keep the counts', () => {
    const uk = pieceText(piece('G5-textbook-sphere').lines, { dialect: 'compact', terms: 'uk', hand: 'right' });
    expect(uk[0]).toBe('Rnd 1: 6 dc in MR (6)');
    expect(uk[2]).toBe('Rnd 3: (dc, inc) x 6 (18)');
  });

  it('the jog note is printed on a line of its own after the round (MR before a BLO round; inc in each st around)', () => {
    const a = placePiece({ counts: [6, 12, 12], loops: ['both', 'BLO', 'both'], start: { k: 'mr', n: 6 } });
    const ta = pieceText(a, { dialect: 'compact', terms: 'us', hand: 'right' });
    expect(ta.slice(0, 3)).toEqual(['Rnd 1: 6 sc in MR (6)', 'Rnd 2 is worked in back loops only; a small jog shows at center back where it begins.', 'Rnd 2: BLO inc in each st around (12)']);
    const b = placePiece({ counts: [6, 12, 18], loops: ['both', 'both', 'FLO'], start: { k: 'mr', n: 6 } });
    const tb = pieceText(b, { dialect: 'compact', terms: 'us', hand: 'right' });
    expect(tb[1]).toBe('Rnd 2: inc in each st around (12)');
    expect(tb[2]).toBe('Rnd 3 is worked in front loops only; a small jog shows at center back where it begins.');
  });
});
